version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '5000:5000'
    volumes:
      - '.:/app'
      - '/app/node_modules/'
    environment:
      - NODE_ENV=development
      - API_URL=http://server:5000/api
      - MONGODB_URI=mongodb://user:pw@mongodb:27017/db?retryWrites=true&w=majority
    depends_on:
      - mongodb
    command: yarn dev

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  data:
